// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <Rcpp.h>

using namespace Rcpp;

#ifdef RCPP_USE_GLOBAL_ROSTREAM
Rcpp::Rostream<true>&  Rcpp::Rcout = Rcpp::Rcpp_cout_get();
Rcpp::Rostream<false>& Rcpp::Rcerr = Rcpp::Rcpp_cerr_get();
#endif

// haversine_vec
NumericVector haversine_vec(NumericVector lon1, NumericVector lat1, double lon2, double lat2);
RcppExport SEXP _SatTagSim_haversine_vec(SEXP lon1SEXP, SEXP lat1SEXP, SEXP lon2SEXP, SEXP lat2SEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericVector >::type lon1(lon1SEXP);
    Rcpp::traits::input_parameter< NumericVector >::type lat1(lat1SEXP);
    Rcpp::traits::input_parameter< double >::type lon2(lon2SEXP);
    Rcpp::traits::input_parameter< double >::type lat2(lat2SEXP);
    rcpp_result_gen = Rcpp::wrap(haversine_vec(lon1, lat1, lon2, lat2));
    return rcpp_result_gen;
END_RCPP
}
// nearest_index
int nearest_index(NumericVector grid, double x);
RcppExport SEXP _SatTagSim_nearest_index(SEXP gridSEXP, SEXP xSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericVector >::type grid(gridSEXP);
    Rcpp::traits::input_parameter< double >::type x(xSEXP);
    rcpp_result_gen = Rcpp::wrap(nearest_index(grid, x));
    return rcpp_result_gen;
END_RCPP
}
// find_next_sst_cpp
NumericVector find_next_sst_cpp(double start_lon, double start_lat, NumericVector sst_lon, NumericVector sst_lat, NumericVector sst_vals, double sstol, double expand_step, int max_iter);
RcppExport SEXP _SatTagSim_find_next_sst_cpp(SEXP start_lonSEXP, SEXP start_latSEXP, SEXP sst_lonSEXP, SEXP sst_latSEXP, SEXP sst_valsSEXP, SEXP sstolSEXP, SEXP expand_stepSEXP, SEXP max_iterSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< double >::type start_lon(start_lonSEXP);
    Rcpp::traits::input_parameter< double >::type start_lat(start_latSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type sst_lon(sst_lonSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type sst_lat(sst_latSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type sst_vals(sst_valsSEXP);
    Rcpp::traits::input_parameter< double >::type sstol(sstolSEXP);
    Rcpp::traits::input_parameter< double >::type expand_step(expand_stepSEXP);
    Rcpp::traits::input_parameter< int >::type max_iter(max_iterSEXP);
    rcpp_result_gen = Rcpp::wrap(find_next_sst_cpp(start_lon, start_lat, sst_lon, sst_lat, sst_vals, sstol, expand_step, max_iter));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_SatTagSim_haversine_vec", (DL_FUNC) &_SatTagSim_haversine_vec, 4},
    {"_SatTagSim_nearest_index", (DL_FUNC) &_SatTagSim_nearest_index, 2},
    {"_SatTagSim_find_next_sst_cpp", (DL_FUNC) &_SatTagSim_find_next_sst_cpp, 8},
    {NULL, NULL, 0}
};

RcppExport void R_init_SatTagSim(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
