# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

haversine_vec <- function(lon1, lat1, lon2, lat2) {
    .Call('_SatTagSim_haversine_vec', PACKAGE = 'SatTagSim', lon1, lat1, lon2, lat2)
}

nearest_index <- function(grid, x) {
    .Call('_SatTagSim_nearest_index', PACKAGE = 'SatTagSim', grid, x)
}

find_next_sst_cpp <- function(start_lon, start_lat, sst_lon, sst_lat, sst_vals, sstol, expand_step = 10.0, max_iter = 20L) {
    .Call('_SatTagSim_find_next_sst_cpp', PACKAGE = 'SatTagSim', start_lon, start_lat, sst_lon, sst_lat, sst_vals, sstol, expand_step, max_iter)
}

